import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import NavBar from "@/components/NavBar/NavBar";
import "@fontsource/poppins";
import "@fortawesome/fontawesome-free/css/all.css";
import ScrollToTop from "@/components/ScrollToTop/ScrollToTop";
import Footer from "@/components/Footer/Footer";
import ResumeInfoProvider from "@/context/ResumeInfoContext";
import ThemeProvider from "@/context/Theme.context";
import FontFamilyProvider from "@/context/FontFamily.context";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NavBar />

        <ResumeInfoProvider>
          <FontFamilyProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </FontFamilyProvider>
        </ResumeInfoProvider>
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
